version: '3'
services:
  db:
    image: postgres:9.4.1
    # ports:
    #  - "5432:5432"

  web:
    image: rails-api
    command: bundle exec rails s -p 5000 -b '0.0.0.0'
    volumes:
      # share files
      - .:/usr/src/app
      # cache gem bundle
      - ruby_gems:/usr/local/bundle
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres@db:5432/development
      - TEST_DATABASE_URL=postgres://postgres@db:5432/test
volumes:
  ruby_gems: {}
